### PR TITLE
Add danish translation

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by scootergrisen** [comment]
I have not idea why i get "This branch has conflicts that must be resolved" here.

**Comment by JakeSmarter** [comment]
> I have not idea why i get "This branch has conflicts that must be resolved" here.

You have duplicated—probably by accident—commit 2dcea99c2db5b1959915916015dd77b8601ac97f with commit eb74e56071af3564bf9cd623f284921b9f522189 on your work branch. To resolve the conflict you have to rebase your commit ee4fe5892d9873e125d7bb5f6c476e49cca7915d on commit 2dcea99c2db5b1959915916015dd77b8601ac97f.

Please note that pull requests here will not go upstream. This is a *private* repository. If you want to contribute to IcedTea-Web please post your patches to the distro-pkg-dev@openjdk.java.net mailing list.

**Comment by scootergrisen** [comment]
I will make a new pull request.
I don't know how to do rebase.

**Comment by scootergrisen** [comment]
I created https://github.com/GITNE/icedtea-web/pull/18 instead.

**Pull request closed without merging**
